apiVersion: v1
kind: Service
metadata:
  name: iframeyouu-backend-service
spec:
  selector:
    app: iframeyouu-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
