apiVersion: apps/v1
kind: Deployment
metadata:
  name: iframeyouu-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iframeyouu-frontend
  template:
    metadata:
      labels:
        app: iframeyouu-frontend
    spec:
      containers:
      - name: frontend
        image: iframeyouu/frontend:latest
        ports:
        - containerPort: 80
