apiVersion: v1
kind: Service
metadata:
  name: iframeyouu-frontend-service
spec:
  selector:
    app: iframeyouu-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
